### ISSUE TITLE
v0.12 is broken with Python 3.5

### ISSUE THREAD

**Issue by arekfu** [matplotlib/pytest-mpl#110]
The README declares that this plugin is compatible with Python 3.5, but v0.12 contains several f-string interpolations (for example [plugin.py:275](https://github.com/matplotlib/pytest-mpl/blob/01c5ec39caa5001d700c7819628b57c798f1e2bb/pytest_mpl/plugin.py#L275)), which are not supported in 3.5. This results in a `SyntaxError`:
```
[... snipping most of the stack trace ...]
   File "/path/to/tox/work/py35/lib/python3.5/site-packages/pytest_mpl/plugin.py", line 275
     raise ValueError(f"The mpl summary type '{generate_summary}' is not supported.")
                                                                                   ^
 SyntaxError: invalid syntax
```

**Comment by Cadair** [comment]
We did drop support for 3.5 in 0.12 (https://github.com/matplotlib/pytest-mpl/blob/master/CHANGES.md#012-2020-11-05) but we should have updated the readme, and also put the supported versions in setup.cfg. That was an oversight on my part. Thanks for the bug report.

**Comment by arekfu** [comment]
Thanks. Do you know if it is possible to fix the version on PyPI somehow so it has the correct metadata in setup.cfg?

**Comment by Cadair** [comment]
I will push a new version and then pull the current on so it doesn't get picked up by at least new versions of pip.

**Comment by arekfu** [comment]
Thanks, that's great!

**Comment by henryiii** [comment]
That would be great, this still seems to be incorrect. It needs a python_requires setting, and the README should be updated too.

**Comment by Cadair** [comment]
I have now yanked the 0.12 release and uploaded 0.12.1 with the correct metadata in the setup.cfg file.
