### ISSUE TITLE
v11.0 py3-only wheel on PyPI actually contains v12.0

### ISSUE THREAD

**Issue by arekfu** [matplotlib/pytest-mpl#113]
The py3-only wheel on PyPI at [this URL](https://files.pythonhosted.org/packages/78/a7/64dc57d2c90dd8ff9a349a039e89f3ca4f97ea5f6767753fdbf2f6ab51ca/pytest_mpl-0.11-py3-none-any.whl), published on 5th November 2020, seems to actually contain the v12.0 code. This breaks pinning `pytest-mpl` to v11.0, which is a necessary workaround for those who unfortunately need to keep Python 3.5 alive (me). See also issue #110.

**Comment by Cadair** [comment]
Thanks for the heads up I have now pulled the wheel. (Sorry it took so long).
