### ISSUE TITLE
Word wrap for error messages is inconsistent to rest of plugin

### ISSUE THREAD

**Issue by theRealSuperMario** [matplotlib/pytest-mpl#116]
```
=================================== FAILURES ===================================
__________________________________ test_plot ___________________________________
Hash for test 'tests.test_foo.test_plot' not found in /private/var/folders/22/9bg1pbnd06l6g69y8gzngf8c0000gn/T/pytest-of-xxx/pytest-96/test_missing_hash0/mpl_generate_dir/baseline_hashes.json. Generated hash is ce07de6b726c3b01afb03aa7c9e939d584bc71a54b9737d69853a0d915cd6181.
=========================== short test summary info ============================
FAILED tests/test_foo.py::test_plot
========================= 1 failed, 2 passed in 1.43s ==========================
```

It should be the regular 80 characters wrap

**Comment by ConorMacBride** [comment]
Pytest should be automatically detecting the terminal width and setting the width of its own output to that, which can be >80 characters. Most, if not all, terminals will already wrap the text (and alternatively, I don't think we should be truncating the output of pytest-mpl either). The output shown looks like pytest was run in a small terminal window, with the window resized after running. I will close this but feel free to reopen if I have missed anything. Thanks :)
