### ISSUE TITLE
Combining `--mpl-hash-library` and `--mpl-generate-hash-library` not working

### ISSUE THREAD

**Issue by dstansby** [matplotlib/pytest-mpl#119]
Currently combining the `--mpl-hash-library` and `--mpl-generate-hash-library` options means the tests all pass, even if some of the existing hashes are incorrect. Instead, I think combining these options should

1. Run the tests as usual (including failing) using the hash library specified by `--mpl-hash-library`
2. Generate a new (correct) hash library using the hash library specified by `--mpl-generate-hash-library`

**Comment by Cadair** [comment]
I think the current behaviour is borrowed from the way the plugin works with images. If you ask it to generate the reference images, all the tests pass and a new set of reference images is generated. I am not sure we really want to make the behaviour different for images and hashes.

**Comment by dstansby** [comment]
That seems sensible if you are *only* requesting a new set of hashes, but it would be nice to fail the tests too if you are requesting a comparison via the `--mpl-hash-library` flag.

The overarching goal here is to be able to run tests against a pre-existing incorrect hash file that:
- Fail, because the original hash file is incorred
- Output a new hash file, making it easy to replace the old incorrect one

**Comment by Cadair** [comment]
I agree it's a good idea, but we would also need to change the reference image behaviour at the same time.
