### ISSUE TITLE
Take into account matplotlib versions

### ISSUE THREAD

**Issue by astrofrog** [matplotlib/pytest-mpl#12]
As matplotlib evolves, it's inevitable that the exact rendering of the output will change. It would therefore be nice to have a way to take this into account by having support for multiple versions of baseline images if necessary.

**Comment by cdeil** [comment]
The matplotlib 2.0 release with a new style is supposed to come out in September (http://matplotlib.org/style_changes.html)

If I understand correctly this will break the image comparison tests of any project that doesn't define their own style for the users / dev that move on to 2.0?

@astrofrog Can you mention this and give a recommendation how to handle this in the README?

**Comment by astrofrog** [comment]
@cdeil - yes, this is my top priority for this package. I think it will depend whether they change any defaults that aren't controllable via rc parameters. If this is all done via rc parameters, then one solution is to simply save the rc parameters alongside the reference image.

However, there are sometimes other changes in rendering, and for those I can't think of anything except than to say that reference images have a range of validity in MPL versions and to then allow developers to provide multiple reference images to cover the different ranges.

**Comment by cdeil** [comment]
@astrofrog – Can you ask this question about rc parameters on the MPL list?

I need a solution for `astroplan` now, i.e. I want to implement the image comparison tests today.
@astrofrog – If you had to do it, which file(s) from matplotlib or seaborn or [astropy](https://github.com/astropy/astropy/blob/master/astropy/visualization/mpl_style.py) would you copy to try and get a reproducible style that has all parameters set?

**Comment by astrofrog** [comment]
@cdeil - I'm on vacation this week so won't be able to do anything concrete until next week.

For now, you can make use of ``mpl.rc_context`` to control the RC parameters for the test, and use ``mpl.rcParamsDefault`` in that context manager to get the current MPL defaults. This will at least guarantee that the results are the same on all MPL < 2.0.

**Comment by dopplershift** [comment]
I've run into this now as I've tried to get my tests running with matplotlib 2.0b1. You have the ability to easily specify the stylesheet using a context manager, and the `classic` style is available to force things back to the old look:
```python
from matplotlib import style
import matplotlib.pyplot as plt
with style.context('classic'):
    plt.plot([1, 2, 3])
    plt.savefig('test.png')
```
The problem is that (currently at least), the call to `savefig` needs to be within the context because there are a few properties that aren't checked until draw time (see matplotlib/matplotlib#6592).

One solution would be to allow specifying the style as an argument to `mpl_image_compare`; that would make sure the call to `savefig` is wrapped appropriately.

**Comment by astrofrog** [comment]
@dopplershift - good idea about having the style be passed as an argument - would you be interested in contributing a patch?

**Comment by dopplershift** [comment]
Sure. One question: what's the minimum version of matplotlib that needs to be supported? I've found a few oddities, at least on 1.4, so it's good to know where to cut off my testing.

**Comment by astrofrog** [comment]
Good question - I would like to keep support for 1.4 and 1.5 once 2.0 comes out. However, we could always make it so that if a person doesn't use the style keyword, then then could use older versions (and if supporting the keyword on 1.4 is problematic, you could limit that to 1.5).

**Comment by dopplershift** [comment]
I'm a bit busy ATM, but am happy to do it when I find some spare cycles (just may be a week or so).

**Comment by astrofrog** [comment]
This has now been done in Done in #20
