### ISSUE TITLE
pytest-mpl can't be used with --open-files option

### ISSUE THREAD

**Issue by cdeil** [matplotlib/pytest-mpl#13]
This was one of the issues I ran into when implementing image comparison tests for astroplan (https://github.com/astropy/astroplan/pull/83#issuecomment-136129489), but I wanted to make an issue for it here so that it's not forgotten.

See https://travis-ci.org/astropy/astroplan/jobs/77905171#L725

```
 AssertionError: File(s) not closed:
/home/travis/miniconda/envs/test/lib/python2.7/site-packages/matplotlib/mpl-data/fonts/ttf/Vera.ttf
/home/travis/miniconda/envs/test/lib/python2.7/site-packages/astropy/tests/pytest_plugins.py:460: AssertionError
```

So apparently matplotlib leaves some font files open and thus `pytest-mpl` can't be used together with the Astropy `--open-files` option.
(For now I've removed `--open-files` from the Astroplan tests as a temp workaround.)

@mdboom or @astrofrog – Is this something that can be fixed in matplotlib or pytest-mpl or just a fact of life?

**Comment by mdboom** [comment]
The open-files support in astropy could be modified to ignore font files, I suppose.  Keeping font files open between draws is an important optimization in matplotlib, I'm afraid (though it will only keep a certain number open before it starts closing them to avoid leaking file handles unboundedly).

**Comment by astrofrog** [comment]
I'm surprised we haven't run into that with tests in Astropy that use Matplotlib.

**Comment by mdboom** [comment]
It might only be triggered if a test causes a new font to load during the course of the test (as might happen during mathtext rendering, for example).  `--open-files` only compares the number of files open before and after the test.  The default font is usually always loaded at startup, so if that doesn't change during the test it wouldn't be considered a "leaking" open file.

**Comment by astrofrog** [comment]
So maybe the key is to make sure that we load the fonts before the tests are run, as part of the pytest plugin.

**Comment by cdeil** [comment]
Concerning the fonts, it's probably unrelated, but just in case not:
I'm writing a Flask web app that generates mpl images (like this: https://github.com/gammapy/gammapy/pull/352/files#diff-a0f8de19c77677a767090877bd431454R83) and this does leave the same font file I mentioned above (`/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/matplotlib/mpl-data/fonts/ttf/Vera.ttf`) open per page load, i.e. if I generate the same image 10 times, the Activity app on my Mac shows the file is opened 10 times. Shouldn't mpl only open the file once?

**Comment by mdboom** [comment]
Definitely seems like a bug.  Can you create an issue for matplotlib?

**Comment by astrofrog** [comment]
@cdeil - how do you see what files a process has open in activity monitor?

**Comment by cdeil** [comment]
@mdboom – I'll try to find time on the weekend to create a simple standalone test case and if it's still there file a MPL issue.

@astrofrog – [how to see the open files in activity monitor](http://osxdaily.com/2012/05/05/see-what-files-ports-an-application-is-using-with-activity-monitor/)

**Comment by nstarman** [comment]
I'm having this same problem with open font files when running tests with Astropy LTS. Has a fix been implemented? Any suggestions?

**Comment by pllim** [comment]
We retired pytest-openfiles plugin. This can be closed.
