### ISSUE TITLE
Hybrid mode is always comparing to baseline images

### ISSUE THREAD

**Issue by ConorMacBride** [matplotlib/pytest-mpl#132]
When using the hybrid mode it is documented that "the baseline images [are] only used if the hash
comparison fails" and "if the hashes match, the baseline images won't be retrieved". Changes introduced in #108 mean that if a baseline directory is specified, they are always downloaded and compared against (but they do not influence the test result). The `--results-always` behaves as documented, but the hybrid mode doesn't.

Steps to fix:
1. Only download and compare baseline image if `--results-always` not set and hash comparison failed.
2. If generating a HTML summary, don't prune the result image that the hash comparison test creates. (To keep the effect that #131 would add.)

Should be a small enough fix. Probably best to not do a release until I fix this? Should have some time tomorrow evening.

**Comment by Cadair** [comment]
Please go ahead. Sounds like a good fix, I think I was just lazy in #108
