### ISSUE TITLE
Fix pytest-mpl GitHub Pages config

### ISSUE THREAD

**Issue by ConorMacBride** [matplotlib/pytest-mpl#140]
Some pytest-mpl tests need to access `http://matplotlib.github.io/pytest-mpl/2.0.x/test_succeeds_remote.png` however a 404 is returned (after 301 redirecting to `https://matplotlib.org/pytest-mpl/2.0.x/test_succeeds_remote.png`). Could someone check that GitHub Pages is enabled in the repo settings? Maybe there has been a change at the organisation level? I can't remember if the custom domain was configured before.

**Comment by Cadair** [comment]
GH pages is configured, and the domain appears to be setup from the org level, so I have asked in the main mpl chat.

**Comment by tacaswell** [comment]
Ah, sorry, we missed this when we moved to self-hosting the docs (the main mpl docs were getting to big to deploy via gh pages!).

https://github.com/matplotlib/matplotlib.org/pull/16 needs to be merged and we need to add a webhook to tell the new server to clone pytest-mpl when there is a push to gh-pages.

attn @QuLogic

**Comment by QuLogic** [comment]
I had this on my list, but the branch hasn't been updated in 4 years, so I thought you weren't using it.

**Comment by QuLogic** [comment]
This is online now.

**Comment by Cadair** [comment]
Thanks very much @QuLogic & @tacaswell :rocket:
