### ISSUE TITLE
HTML report links should be relative, not absolute

### ISSUE THREAD

**Issue by FaustinCarter** [matplotlib/pytest-mpl#141]
In order to make the generated html reports portable, the links generated in the html code should be relative to the `results_dir` directory. Instead, as can be seen, they are absolute.

https://github.com/matplotlib/pytest-mpl/blob/54510c59f58edf356d728688f9653771791cb15e/pytest_mpl/summary/html.py#L229

This makes it impossible to, say, generate an html report as part of an automated test pipeline, and have that report be usable as a build artifact.

**Comment by ConorMacBride** [comment]
Hi @FaustinCarter, the links in the HTML report should already be relative. See for example:

https://github.com/matplotlib/pytest-mpl/blob/54510c59f58edf356d728688f9653771791cb15e/pytest_mpl/summary/templates/base.html#L6

And this produces a working build artifact, for example here: https://76114-2165383-gh.circle-artifacts.com/0/.tmp/py38-figure/figure_test_images/fig_comparison.html

The line you show is from the code which copies the CSS and JavaScript files etc. from the absolute path of the installed pytest-mpl package data into the absolute path of the `results_dir`. However, any links to `results_dir` within the generated HTML itself should already be relative. What error message are you seeing?

There was a bug in a recent version of setuptools which may have affected this package. Can you make sure it's not using setuptools 61.0.0? If you're not getting any error messages during the test pipeline, maybe only `fig_comparison.html` is being saved as a build artifact and not the whole `results_dir`?

**Comment by FaustinCarter** [comment]
Alright, I think I must have done something dumb. Closing this as you are clearly right and it produces a report with relative file refs!
