### ISSUE TITLE
Diffs for images with different sizes ?

### ISSUE THREAD

**Issue by neutrinoceros** [matplotlib/pytest-mpl#147]
I would like to migrate some existing image comparison to use this pytest plugin, but it seems to me that there is currently no way to produce a diff for images with differences in pixel sizes. In the project-specific framework I want to migrate away from, this is a useful feature we support by making the diff buffer's shape `max(im1.shape, im2.shape)` in both direction, and overlap the top left corner of everything.
I'm considering contributing something similar here. Would such a feature be considered for inclusion or would that be considered bad in any way ?
Thanks !

**Comment by astrofrog** [comment]
I don't think there would be any harm in producing a diff in this case?

**Comment by neutrinoceros** [comment]
Actually I figured that the _reason_ for supporting this in the project-specific framework I want to migrate away from is that nothing is reported unless a diff is successfully produced. In pytest-mpl, you still get a useful report if images are different in size, since you get to see the baseline and the current result. Now I don't think implementing my suggestion is worth any potential (unforeseen) downsides.
