### ISSUE TITLE
clarify --mpl-generate-hash-library location in README.rst

### ISSUE THREAD

**Issue by bjlittle** [matplotlib/pytest-mpl#155]
The current `README.rst` doesn't explicitly mention where the hash library will be created i.e.,

![image](https://user-images.githubusercontent.com/2051656/169422847-94532a8d-678d-4876-95a6-3d941fddbbe9.png)

At present the provided hash library file will be created at the root of the package.

I'm happy to add this clarification, if you agree this is useful?

**Comment by Cadair** [comment]
Does it always generate in the root of the repo or can you specify a path in that cli flag?

**Comment by ConorMacBride** [comment]
There is documentation in `plugin.py` but this should be added to the readme.
https://github.com/matplotlib/pytest-mpl/blob/e3876180847c2d04aeda1982372074998a7f8716/pytest_mpl/plugin.py#L100-L102
