### ISSUE TITLE
Adopt black

### ISSUE THREAD

**Issue by bjlittle** [matplotlib/pytest-mpl#156]
Would you be willing to adopt the [black](https://github.com/psf/black) code formatting standard?

If so, then I'd happily setup the `pre-commit` hook and blackify the code base 👍

**Comment by Cadair** [comment]
I am not a massive fan of black personally, although I do a agree the style of this plugin could be improved. I would be up for seeing a diff of black + isort with pre-commit and then we can decide if black is the way forward or we just use flake8 or something in the pre-commit to keep a better lid on things?

**Comment by dopplershift** [comment]
I'm not a huge fan of black either (it produces ugly code, especially for functions with lots of params), but I feel like I'm losing that battle. I would say that if we do, we should configure the line length for something > 80 columns. It's 2022, we can have a few more columns than vt100 let us have.
