### ISSUE TITLE
Adding more pytest-mpl maintainers

### ISSUE THREAD

**Issue by Cadair** [matplotlib/pytest-mpl#168]
@ConorMacBride has been making lots of valuable contributions and @bjlittle expressed interest in helping out (https://github.com/matplotlib/pytest-mpl/pull/150#issuecomment-1146436668) so could you add them @dopplershift or @tacaswell ?

**Comment by Cadair** [comment]
Also you good with this @astrofrog ?

**Comment by astrofrog** [comment]
Yep!

**Comment by tacaswell** [comment]
Invitations are out, but I think both @Cadair and @astrofrog should have the power to invite collaborators to pytest-mpl (which is slightly different than adding to the org).

**Comment by bjlittle** [comment]
@Cadair @astrofrog @dopplershift and @tacaswell Thanks so much 🥳🎉🍻
