### ISSUE TITLE
Have you considered using a perceptual hash for comparing images?

### ISSUE THREAD

**Issue by DougBurke** [matplotlib/pytest-mpl#21]
I've got a tab open at https://github.com/commonsmachinery/blockhash-python and have tested it out on a whole 1 line plot, and it seems to do okay. It might be interesting to support something like this as an option (although I note that this particular perceptual hash has notes that it doesn't do too well with images containing large areas of a single color, which is kind of de rigueur for plots)

**Comment by ConorMacBride** [comment]
Closing as this is being discussed further in #146
