### ISSUE TITLE
Pluggy 1.4.0 now warns about deprecated hook wrapper style

### ISSUE THREAD

**Issue by neutrinoceros** [matplotlib/pytest-mpl#221]
Pluggy 1.4.0 was released a couple hours ago.
It nows warns about old-style hook wrappers:
https://github.com/matplotlib/pytest-mpl/blob/db0ea3699f639f882813b02ce65ee9e676fc7caa/pytest_mpl/plugin.py#L762-L763
https://github.com/matplotlib/pytest-mpl/blob/db0ea3699f639f882813b02ce65ee9e676fc7caa/pytest_mpl/plugin.py#L930-L931

See the [release notes](https://pluggy.readthedocs.io/en/stable/changelog.html#features) and [docs](https://pluggy.readthedocs.io/en/stable/index.html#wrappers).

**Comment by pllim** [comment]
Hmm, so the `force_exception` added in https://github.com/matplotlib/pytest-mpl/pull/219 didn't fix this problem? Does that mean #216 is needed sooner than later?

**Comment by neutrinoceros** [comment]
#219 fixed an incompatibility with pytest 8.1, but the new warning is coming from pluggy itself.

I supposed this could be closed as a dupe of #216 actually. Sorry about the noise !

**Comment by pllim** [comment]
@neutrinoceros , are you sure #219 didn't fix the problem in astropy ? CircleCI is also green with dev version of pytest-mpl . Maybe instead of implementing #216 , all we need is a new release of pytest-mpl (which would be faster to do and is needed anyway since the last release was 2 years ago).

**Comment by pllim** [comment]
Now I am confused, see https://github.com/astropy/astropy/pull/15929#issuecomment-1908720762

**Comment by neutrinoceros** [comment]
Well I'm sure that #216 needs to happen to fix the problem I reported here, but I'm as confused as you are regarding the apparent flakiness of CI.
I also don't get how #219 is supposed to fix astropy's CI if it's not released yet.

**Comment by pllim** [comment]
> is supposed to fix astropy's CI if it's not released yet

It cannot officially "fix the CI" but would indicate a new patch here isn't necessary, just a new release. But again, maybe I was just lucky that it passed using dev version of pytest-mpl if the failures don't pop up all the time. 🤷‍♀️

**Comment by ConorMacBride** [comment]
If the only error you are seeing is [`PluggyTeardownRaisedWarning`](https://pluggy.readthedocs.io/en/stable/api_reference.html#pluggy.PluggyTeardownRaisedWarning), that should be fixed on the the `main` branch of `pytest-mpl`. The [pluggy release notes](https://pluggy.readthedocs.io/en/stable/changelog.html#features) links the new warning to https://github.com/pytest-dev/pluggy/issues/463, which was motivated by me seeing a misleading error message in https://github.com/pytest-dev/pytest/issues/11714.

When I was seeing that error before (i.e. error raised in teardown) it was very flaky. It appeared in different tests every time I ran pytest. If you temporarily replace `image: pytest-mpl` with `image: git+https://github.com/matplotlib/pytest-mpl.git` in `/tox.ini` in https://github.com/astropy/astropy/pull/15929 and allow pluggy 1.4, the image tests will hopefully run without any issues.

There's just one PR that needs reviewed and merged before a new `pytest-mpl` release can be published.

**Comment by neutrinoceros** [comment]
Thanks a lot for the clarification @ConorMacBride !
