### ISSUE TITLE
Remove dependency on nose

### ISSUE THREAD

**Issue by astrofrog** [matplotlib/pytest-mpl#25]
We currently depend on functions in matplotlib that depend on nose. It would be nice to avoid that dependency since it means having two testing frameworks installed.

**Comment by mcepl** [comment]
> We currently depend on functions in matplotlib that depend on nose.

Where? If I search through whole repository I haven’t found one place where nose would be imported. If matplotlib requires it, it is its business to require it.

**Comment by dopplershift** [comment]
Well, we depend on matplotlib for its testing stuff, which depended on nose--but that's not part of matplotlib's core dependencies since it's only for testing.

This seems to be less of a problem with Matplotlib >3.2 since all of the nose stuff has been removed. Not sure how we reasonably specify that from a packaging perspective, though.

**Comment by mcepl** [comment]
> This seems to be less of a problem with Matplotlib >3.2 since all of the nose stuff has been removed. Not sure how we reasonably specify that from a packaging perspective, though.

Just tell me, how to cause any issue by not having nose installed. I haven’t found a way.

**Comment by ConorMacBride** [comment]
Our test suite running on `matplotlib>=2.1` passes without nose being installed. We only force nose to be installed for our matplotlib 2.0 tests (and we should probably drop that old version anyway):

https://github.com/matplotlib/pytest-mpl/blob/3aeb3dd9ab7bb1d319bfede4b5a78767cbb4581e/tox.ini#L21

I assume that, while the `matplotlib<=3.2` test suite may depend on nose, as of `matplotlib>2.0`, pytest-mpl no longer uses any part of matplotlib which depend on nose. And matplotlib (at least >=2.0) does not force nose to be installed.

So I think this issue can be closed as it's already "fixed" by matplotlib?
