### ISSUE TITLE
0.6 release?

### ISSUE THREAD

**Issue by dopplershift** [matplotlib/pytest-mpl#29]
Any concrete plans for what would need to land for a 0.6 release? Some interesting things have landed since 0.5, like `remove_text` and `style` support.

**Comment by astrofrog** [comment]
Yes, I'd like to do a release ASAP, hoping to get to it early next week.

**Comment by bsipocz** [comment]
in the meantime I've noticed that the release tags are missing here for v0.5 (I guess as it was released very shortly after v0.4)

**Comment by astrofrog** [comment]
@bsipocz - good point, will try and push that before doing the 0.6 release.

**Comment by astrofrog** [comment]
0.6 and 0.7 are out!

**Comment by bsipocz** [comment]
0.7? It's impossible to keep up with you :)

**Comment by astrofrog** [comment]
Haha sorry - not much changed really. I'm inspired by setuptools ;)

**Comment by bsipocz** [comment]
No worries, I actually quite like the setuptools philosophy. And sorting out a bot to do the updates is really my next hack day project.
