### ISSUE TITLE
1.4 pollutes output

### ISSUE THREAD

**Issue by dopplershift** [matplotlib/pytest-mpl#36]
When running on matplotlib 1.4 with the `classic.mplstyle` file, the output (either when a test fails or when running `pytest -s`) is filled with messages like:
```
Bad key "axes.spines.right" on line 219 in
/Users/rmay/miniconda3/envs/legacy/lib/python2.7/site-packages/pytest_mpl/classic.mplstyle.
You probably need to get an updated matplotlibrc file from
http://matplotlib.sf.net/_static/matplotlibrc or from the matplotlib source
distribution
```
Given that this file is *only* used on matplotlib 1.4, would it make sense to remove all of the lines matplotlib 1.4 doesn't understand? I'm guessing most of these are new rcParams for 1.5/2.0.

**Comment by astrofrog** [comment]
@dopplershift - yes, we should definitely do this. Do you have time to do a PR?

**Comment by dopplershift** [comment]
Yeah, can do.
