### ISSUE TITLE
Take action after failure on Travis?

### ISSUE THREAD

**Issue by fmaussion** [matplotlib/pytest-mpl#40]
Hi, 

thanks for pytest-mpl! I'd like to know if it's possible to upload the result images somewhere after failure on Travis. Our tests on Travis fail for an unknown reason (RMS of the order of magnitude of 8), and I'd like to have a look at the images.

**Comment by bsipocz** [comment]
You can use the ``after_failure`` section in your ``.travis.yml`` file to define actions after the tests failed. See usage here: https://docs.travis-ci.com/user/customizing-the-build

**Comment by fmaussion** [comment]
thanks for the rapid answer! is there a way to know where the tested images are  lcoated, or should I upload the entire /tmp folder somewhere?

**Comment by bsipocz** [comment]
@fmaussion - I'm not sure about the default, but it seems that there is a command line option ``--mpl-generate-path`` where you can define the location.

**Comment by fmaussion** [comment]
@bsipocz thanks, but as far as I understand ``--mpl-generate-path`` is a way to build the baseline images. How do I control where the test images are put during the test? My Travis failure log looks like this:

```
Exception: Error: Image files did not match.
  RMS Value: 8.790773137848065
  Expected:  
    /tmp/tmpmhir6z_u/baseline-test_centerlines.png
  Actual:    
    /tmp/tmpmhir6z_u/test_centerlines.png
  Difference:
    /tmp/tmpmhir6z_u/test_centerlines-failed-diff.png
  Tolerance: 
    2
```
I was wondering if I can also have control on the cryptic ``/tmp/tmpmhir6z_u/`` folder

**Comment by astrofrog** [comment]
There is now an option (available in the developer version and in the next release) called ``--mpl-results-path`` that can help set the main results directory to something deterministic. I've mentioned this now in the [README](https://github.com/matplotlib/pytest-mpl#test-failure-example) and have also given links to docs explaining how to get these files off the continuous integration services.
