### ISSUE TITLE
Slash "/" in test name

### ISSUE THREAD

**Issue by gshiba** [matplotlib/pytest-mpl#44]
My code (simplified)

```python
@pytest.fixture(params=['/some/data1', '/some/data2'])
def dataframe(reqeust):
    return transform(request.param)

@pytest.mark.mpl_image_compare(baseline_dir=BASELINE_DIR)
def test_plot(dataframe):
    fig = my_plotter(dataframe)
    return fig
```

When I run `pytest test_my_plotters.py --mpl --mpl-generate-path=baseline`, I get something like (simplified):

```
IOError: [Errno 2] No such file or directory: '.../baseline/test_plot_/some/data1.png'

../venv/local/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py:532: IOError
```

In short, `print_png` in `matplotlib/backends/backend_agg.py` is failing because the intermediate paths (`.../some/...`) is missing.

This work around seems to work (https://github.com/gshiba/pytest-mpl/commit/3c8aa6e9d6809360d51a791798be19f0224a0cb4) but not sure if this is the right approach.

Thanks

**Comment by astrofrog** [comment]
I'm happy with the fix in #50, thanks!
