### ISSUE TITLE
Support non-PNG extensions

### ISSUE THREAD

**Issue by jnothman** [matplotlib/pytest-mpl#48]
matplotlib's own `image_comparison` "decorator defaults to generating png, pdf and svg output, but in interest of keeping the size of the library from ballooning we should only include the svg or pdf outputs if the test is explicitly exercising a feature dependent on that backend." (from [here](https://github.com/matplotlib/matplotlib/blob/0d5a02a4e118eb098b78ea00039acd06310e54be/doc/devel/testing.rst)).

Only supporting PNG seems very limiting, if not counter-intuitive.

**Comment by astrofrog** [comment]
+1 to supporting other formats - my only limitation in implementing this has been time. If you have time to contribute fixes for this, that would be great!

**Comment by tacaswell** [comment]
I suspect much of the code for doing the other format -> png conversion so that these files can be compared can be directly copied from mpl.

**Comment by andrzejnovak** [comment]
Bump. Is anyone actively working on this? At least pdf?

**Comment by astrofrog** [comment]
I haven’t had a chance to work on this, and probably won’t be able to in the near future
