### ISSUE TITLE
Figures are not closed when pytest is run without --mpl option

### ISSUE THREAD

**Issue by fmaussion** [matplotlib/pytest-mpl#56]
I get this warning when running our graphics tests:
```
RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
    max_open_warning, RuntimeWarning)
```

I assumed that ``pytest`` would close the figures after testing? Or is it the user's responsibility to do so?

Thanks!

**Comment by astrofrog** [comment]
Interesting - we *do* close the figures here:

https://github.com/matplotlib/pytest-mpl/blob/master/pytest_mpl/plugin.py#L200

https://github.com/matplotlib/pytest-mpl/blob/master/pytest_mpl/plugin.py#L231

I wonder what could be happening here. Are you opening any other figures that are not being used for the image testing?

**Comment by fmaussion** [comment]
Sorry I've been away from my desk a long time. Will try to look into it in more detail and let you know.

**Comment by fmaussion** [comment]
OK, the warnings happen when we run pytest *without* the ``--mpl`` option. Some tests in our travis matrix don't run pytest-mpl, so I guess we'll have to build in some plt.close() somewhere if pytest-mpl isn't used. Do you have an idea how to do this in an elegant way? Thanks!

**Comment by astrofrog** [comment]
@fmaussion - I think the best solution my be to end your test functions with:


```
try:
    return fig
finally:
    plt.close(fig)
```

does this help?

**Comment by fmaussion** [comment]
Yes, that does the trick. I'll make a simple decorator for all our graphic tests doing exactly this. thanks!

**Comment by fmaussion** [comment]
... or, isn't this is something the pytest decorator could do too?

**Comment by astrofrog** [comment]
@fmaussion -

**Comment by astrofrog** [comment]
@fmaussion - this is now fixed in pytest-mpl
