### ISSUE TITLE
Non-matplotlib figure objects need more than savefig

### ISSUE THREAD

**Issue by leouieda** [matplotlib/pytest-mpl#57]
I have been using pytest-mpl to test the [gmt-python](https://github.com/GenericMappingTools/gmt-python) library. We have a `Figure` object that implements `savefig` and the tests were working fine in Python 3.5 and 3.6 ([an example test script](https://github.com/GenericMappingTools/gmt-python/blob/master/gmt/tests/test_pscoast.py)).

A few weeks ago, our tests for 3.5 started failing ([example error log](https://travis-ci.org/GenericMappingTools/gmt-python/jobs/275310274#L1930)). I reproduced the failing tests locally using a 3.5 version of our [default conda environment](https://github.com/GenericMappingTools/gmt-python/blob/master/environment.yml). I managed to track it down to `plt.close` not recognizing my `Figure` class as a valid figure object (see [the pyplot.close code](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/pyplot.py#L646)). 

The real mystery is that the same test with the same matplotlib version (2.0.2) passes on 3.6. 

Is there any way that pytest-mpl could avoid the call to `plt.close(fig)`? Even just removing the `fig` argument to close the current figure would already solve the problem. I can resolve this by introducing a `int` attribute on my `Figure` but that is very ugly.

If there is not way around it, then it would be good to include in the docs the need to implement an `int` attribute to fool `plt.close`. 

Otherwise, I'm very impressed that this worked so flawlessly! Congratulations!

**Comment by astrofrog** [comment]
We can't remove the closing, but we could potentially have a try...except around it since if closing fails it shouldn't stop the tests.

**Comment by astrofrog** [comment]
Fixed in #60 - now only actual Matplotlib figures are closed

**Comment by leouieda** [comment]
@astrofrog that's perfect, thanks!
