### ISSUE TITLE
Hanging when generating images if Inkscape is on path (Windows)

### ISSUE THREAD

**Issue by jat255** [matplotlib/pytest-mpl#63]
Ran into an interesting bug, where my `pytest` command was hanging when using the `--mpl-generate-path` option (note, this is my first time using `pytest-mpl`, so let me know if this is user error...)

I noticed in my task manager that Inkscape was running at full-throttle on one core as a child process of the   `pytest` command, and that killing it would cause the image generation to complete, with the following warning:

```python
 C:\anaconda3\envs\******\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
    return f(*args, **kwds)
```

I'm not sure why Inkscape is being called as part of the building process, but it caused a significant lag (I let it run for about 10 minutes before I killed it, and it hadn't finished). After removing inkscape from my `%PATH%`, my images build, as expected, although still with the same warning as above.

**Comment by jat255** [comment]
I guess this might be an upstream issue, since it looks like the only action this option does is on https://github.com/matplotlib/pytest-mpl/blob/5ca4ca0aae4e341eb0bd157048ace43c0fc548e4/pytest_mpl/plugin.py#L270 with `savefig`

**Comment by astrofrog** [comment]
@jat255 - what format are you using for the reference images? Are you just using the default? (PNG)

**Comment by jat255** [comment]
Yeah, this was with the default PNG format. I'm no longer getting the warning that I mentioned above (I'm not sure why).

Although, now I'm stumped, because I'm not getting that warning anymore, and the images are generating, even when I put Inkscape back on my path, so I guess this must have been some sort of transient issue. Sorry for the bother.
