### ISSUE TITLE
AttributeError: 'mpl_image_compare' not a registered marker

### ISSUE THREAD

**Issue by fredrikw** [matplotlib/pytest-mpl#69]
When I try to use pytest-mpl on py.test version 3.4.2 I get the above error. After some googling, I realized that I could solve the problem by adding the following line as the first line in plugin.py/pytest_configure(), line 99
`config.addinivalue_line('markers', "mpl_image_compare: Compares images from matplotlib")`
I have not found out if there is a recent change in pytest or if something else is going on but it works for me...

**Comment by jorgepiloto** [comment]
I am getting the same error and my pytest version is 4.0.2. Not sure how to solve this problem either :confused:

**Comment by dopplershift** [comment]
That's interesting. I'm not seeing this problem with pytest 4.4 and pytest-mpl 0.10.

**Comment by jorgepiloto** [comment]
After adding `mpl_image_compare` under the section of [tool:pytest] markers in my setup.cfg I was finally able  to run successfully all the tests :relaxed:

**Comment by phobson** [comment]
To clarify the above fix for those still getting on their feet with pytst, the relevant section of my setup.cfg looks like this:

```
[tool:pytest]
markers =
    mpl_image_compare
```
