### ISSUE TITLE
Status of pytest-mpl?

### ISSUE THREAD

**Issue by fmaussion** [matplotlib/pytest-mpl#73]
Hi all, 

we adopted pytest-mpl instead of maptlotlib's homegrown decorator at the time where mpl was still depending on nose: thanks for this great tool!

I also thought that the purpose of pytest-mpl was to replace the mpl testing internals in order to avoid duplicated code when MPL would made the switch to pytest, but this didn't happen. So now I wonder: what is the status/purpose of pytest-mpl and the long-term plans? Should we get back to using MPL's ``image_comparison`` decorator instead?

**Comment by bsipocz** [comment]
astropy and related packages are also heavy users of pytest-mpl.

**Comment by fmaussion** [comment]
Thanks for the answers! This is reassuring. I was wondering because the activity is quite low recently.

(we would be keen in getting a new release since https://github.com/matplotlib/pytest-mpl/pull/72 was merged if possible ;)

**Comment by astrofrog** [comment]
It's been a busy summer, but I'll try and get a release out soon!
