### ISSUE TITLE
0.10 release date

### ISSUE THREAD

**Issue by leouieda** [matplotlib/pytest-mpl#75]
@astrofrog is there a plan for making a 0.10 release? I need the fix in #66 and it would be great to get a release so I don't have to tell people to install from github. I'd be more than happy to help make it happen :)

**Comment by astrofrog** [comment]
I'll try and do this shortly!

**Comment by leouieda** [comment]
Thanks @astrofrog! Sorry about the pressure. Let me know if I can help with anything.

**Comment by astrofrog** [comment]
@leouieda - 0.10 is released, let me know if you run into any issues!

**Comment by leouieda** [comment]
Thanks! I'll give it a try.
