### ISSUE TITLE
Testing local changes in rcParams

### ISSUE THREAD

**Issue by moldyn-nagel** [matplotlib/pytest-mpl#88]
I want to test a function which modifies rcParams dynamically depending on the user input. For example
```python
import matplotlib.pyplot as plt

def set_lw(lw):
    plt.rcParams['lines.linewidth'] = lw
```
For static changes, this could be solved by generating a mplstyle and setting `MPLCONFIGDIR`. In my case I want to set, e.g. the cycler dynamically from cmaps, which would result in several thousands different mplstyles. Hence, it is not the way to go.

I would be thankful for any hint or suggestion how to test this kind of function.

**Comment by ConorMacBride** [comment]
I think what you are looking for is:

```py
import pytest
import matplotlib.pyplot as plt


def set_lw(lw):
    plt.rcParams['lines.linewidth'] = lw


@pytest.mark.mpl_image_compare
def test_plot_1():
    set_lw(2)
    fig, ax = plt.subplots()
    ax.plot([1, 3, 2, 4])
    return fig


@pytest.mark.mpl_image_compare
def test_plot_2():
    set_lw(4)
    fig, ax = plt.subplots()
    ax.plot([1, 3, 2, 4])
    return fig
```

This runs as expected for me with `pytest test_rc.py --mpl --mpl-generate-summary=html`. Feel free to reopen if I've misinterpreted the issue :)
