### ISSUE TITLE
pytest-mpl is platform dependent?

### ISSUE THREAD

**Issue by awa5114** [matplotlib/pytest-mpl#91]
I am experimenting with pytest-mpl in combination with bitbucket-pipelines to write unit tests for figure plotting functionality in my code. I am using a Windows 10 machine. The default docker image on bitbucket pipelines uses another platform.

I added a unit test which seems to run successfuly on my local machine. However, when I push this into the remote build it fails. I inspected the output image in the remote build using bitbucket artifacts and the images are ever so slightly different, where the text has a slightly different spacing on the remote build than on my local machine.

How can I get the images to look exactly the same such as the comparison is platform independent?

**Comment by dopplershift** [comment]
This is a general challenge with image testing from matplotlib. A frequent source of this is differences in text, usually due to different versions of freetype being used on the two machines.

**Comment by thomasaarholt** [comment]
I just wrote a PR #93  to clarify this in the readme.

**Comment by Cadair** [comment]
I am going to close this issue because I don't think there is anything we can do about it in pytest-mpl. It's matplotlib / freetype which are platform dependent not pytest-mpl.
