### ISSUE TITLE
Let image baseline directory be relative to where the tests are, not where pytest was run

### ISSUE THREAD

**Issue by dhyams** [matplotlib/pytest-mpl#92]
If I have a directory structure like

```
tests
    component1
         baseline
    component2
          baseline
```

I run pytest in the component1 or component2 directories, things work fine,  But if I run pytest in the tests directory, all tests fails because it is assumed that the baseline directory is relative to where pytest was run.  I'd like to be able to run pytest in either any of these directories (tests, tests/component1, tests/component2).

**Comment by dopplershift** [comment]
Are you setting the path to the baseline images somewhere? By default, I think it does exactly what you want:

https://github.com/matplotlib/pytest-mpl/blob/83266c5374cd4bb9154436eb224dc6cd0f4edc42/pytest_mpl/plugin.py#L226

That's saying look for the baseline images within a directory called `baseline` within the same directory where the test file is located.

**Comment by dhyams** [comment]
Hello sir; it's the other side of the branch that you refer to above (if I'm reading the code correctly) that is happening to me.  I don't set the path on a per-test basis; it's set via the command line option to pytest (--mpl-baseline-path).  I should not have used "baseline" as the directory in my example above; I should have used "data/images" or something else to indicate that I'm setting the --mpl-baseline-path command line option.

I think if the other side of the branch that you refer to above, also prepended os.path.dirname(item.fspath.strpath), that would take care of the issue.  But other people might want the original behavior.  Here's my actual setup


```
tests
   component1      <-- test_* files go here
        data         <--- data files needed for other tests go here
           images  <--- mpl baseline images for component1 go here
           raw
   component2      <-- test_* files go here
       data       <--- data files needed for other tests go here
           images  <--- mpl baseline images for component1 go here
           raw
```

**Comment by dopplershift** [comment]
The only way I can think of to do that (without breaking everyone) is to add a flag that tells pytest-mpl to interpret that argument as test-relative.

**Comment by dhyams** [comment]
Agreed.

**Comment by dhyams** [comment]
PR #96 closes this issue.  I guess I didn't link the pull request to the issue properly...apologies.
